name: auspex
channels:
  - conda-forge
dependencies:
  - python=3.11.6
  - pip
  # - boost=1.74
  - cctbx
  - dials
  - numpy=1.26
  - scipy=1.11
  - scikit-learn=1.3
  - matplotlib
  - mpl-scatter-density
  - msgpack-python
  - tensorflow
  - tabulate
  - mpi4py
  - openmpi
  - pip:
      - nptyping[complete]
